version: "3"
services:
  web:
    build: .
    links:
      - db
    ports:
      - 8080:8080
    command: sh -c "npm install && npm run dev"
    volumes:
      - ".:/app"
    environment:
      HOST: 0.0.0.0

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Super
      MYSQL_DATABASE: m152
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8888:8080
